USE QLDVVanChuyen
GO 
-- xóa dữ liệu

-- tạo bảng TT Hoạt Động
CREATE TABLE TrangThaiHD
(
	Ma_TTHD INT IDENTITY(1,1) PRIMARY KEY,
	TenTTHD NVARCHAR(30) UNIQUE NOT NULL
)

GO

-- tạo bảng Chi Nhánh
CREATE TABLE ChiNhanh
(
	Ma_CN VARCHAR(5) PRIMARY KEY,
	DiaChi NVARCHAR(50) NOT NULL,
	Ma_TTHD INT NOT NULL,

	-- ràng buộc: nếu chi nhánh ngừng hoạt động thì không thể có nhân viên
	-- nếu chi nhánh đang hoạt động thì không thể không có nhân viên làm việc
	FOREIGN KEY (Ma_TTHD) REFERENCES TrangThaiHD,

)

GO

-- tạo bảng Chức Vụ
CREATE TABLE ChucVu
(
	Ma_CV INT IDENTITY(1,1) PRIMARY KEY,
	TenCV NVARCHAR(50) UNIQUE NOT NULL
)
GO

 --tạo bảng TT Làm việc
CREATE TABLE TinhTrangLV
(
	Ma_TTLV INT IDENTITY(1,1) PRIMARY KEY,
	TenTTLV NVARCHAR(30) UNIQUE NOT NULL
)
GO

-- tạo bản nhân viên

CREATE TABLE NhanVien 
(
	Ma_NV VARCHAR(10) PRIMARY KEY,
	TenNV NVARCHAR(30) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10) UNIQUE NOT NULL, -- 2 NHÂN VIÊN KHÔNG THỂ CÓ CÙNG SĐT
	CCCD VARCHAR(12) UNIQUE NOT NULL, -- 2 NV KO THỂ CÙNG CCCD
	Ngay_LV DATE NOT NULL,

	Ma_CN VARCHAR(5) NOT NULL,
	Ma_CV INT NOT NULL,
	Ma_TTLV INT NOT NULL
	FOREIGN KEY (Ma_CN) REFERENCES ChiNhanh(Ma_CN),
	FOREIGN KEY (Ma_CV) REFERENCES ChucVu(Ma_CV),
	FOREIGN KEY (Ma_TTLV) REFERENCES TinhTrangLV(Ma_TTLV)

)

GO
-- TẠO BẢNG KHÁCH HÀNG
CREATE TABLE KhachHang
(
	Ma_KH VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(30) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10) UNIQUE NOT NULL,
	CCCD VARCHAR(12) UNIQUE NOT NULL,
	
)
GO 
-- xóa số lượng ĐH

GO

-- tạo bảng shipper
CREATE TABLE Shippers
(
	Ma_Shipper VARCHAR(10) PRIMARY KEY,
	HoTen NVARCHAR(30) NOT NULL, 
	DiaChi NVARCHAR(50) NOT NULL,
	SDT VARCHAR(10) UNIQUE NOT NULL,
	CCCD VARCHAR(12) UNIQUE NOT NULL,
	Ngay_LV DATE NOT NULL,

	Ma_CN VARCHAR(5) NOT NULL,
	Ma_TTLV INT NOT NULL

	FOREIGN KEY (Ma_CN) REFERENCES ChiNhanh(Ma_CN),
	FOREIGN KEY (Ma_TTLV) REFERENCES TinhTrangLV(Ma_TTLV)
	
)

GO
-- ĐƠN HÀNG
-- tạo bảng trạng thái Đơn hàng

CREATE TABLE TrangThaiDH 
(
	Ma_TTDH INT IDENTITY(1,1) PRIMARY KEY,
	TenTTDH NVARCHAR(50) UNIQUE NOT NULL
)
GO

-- TẠO BẢNG LOẠI HÀNG

CREATE TABLE LoaiHang 
(
	Ma_LH INT IDENTITY(1,1) PRIMARY KEY,
	TenLH NVARCHAR(30) UNIQUE NOT NULL
)

-- TẠO BẢNG ĐƠN HÀNG
CREATE TABLE DonHang
(
	Ma_DH VARCHAR(10) PRIMARY KEY,
	TenDH NVARCHAR(30) NOT NULL,
	Ten_NguoiNhan NVARCHAR(30) NOT NULL,
	SDT_NguoiNhan VARCHAR(10) NOT NULL,
	DiaChi NVARCHAR(50) NOT NULL,
	KichThuoc INT NOT NULL,
	PhiShip MONEY NULL,
	GiaTri MONEY NOT NULL,
	ThanhToan NVARCHAR(50) NULL,
	NgayGiao DATETIME NULL ,
	NgayTao DATETIME NOT NULL,


	Ma_KH VARCHAR(10) NOT NULL,
	Ma_Shipper VARCHAR(10) NULL,
	Ma_LH INT NOT NULL,
	Ma_TTDH INT DEFAULT 1 NOT NULL,

	FOREIGN KEY (Ma_KH)
	REFERENCES KhachHang(Ma_KH),

	FOREIGN KEY (Ma_Shipper)
	REFERENCES Shippers(Ma_Shipper),

	FOREIGN KEY (Ma_LH)
	REFERENCES LoaiHang(Ma_LH),

	FOREIGN KEY (Ma_TTDH)
	REFERENCES TrangThaiDH(Ma_TTDH)

)


GO
-- TẠO BẢNG CẬP NHẬT ĐƠN HÀNG

CREATE TABLE CapNhatDH 
(
	Ma_CNDH INT IDENTITY(1,1) NOT NULL,
	Ma_NV VARCHAR(10) NOT NULL,
	Ma_DH VARCHAR(10) NOT NULL,
	NoiDung NTEXT NOT NULL,
	ThoiGian DATETIME NOT NULL,

	PRIMARY KEY(Ma_CNDH, Ma_NV, Ma_DH),

	FOREIGN KEY (Ma_NV) REFERENCES NhanVien(Ma_NV),
	FOREIGN KEY (Ma_DH) REFERENCES DonHang(Ma_DH)

)

-- tình trạng KN 
GO
CREATE TABLE TinhTrangKN 
(
	Ma_TTKN INT IDENTITY(1,1) PRIMARY KEY,
	NoiDungTTKN	NVARCHAR(50) UNIQUE NOT NULL
) 
GO

--Khiếu nại 
GO 
CREATE TABLE KhieuNai
(
	Ma_KN INT IDENTITY(1,1) PRIMARY KEY,
	NoiDungKN NTEXT NOT NULL,
	NgayGui DATETIME NOT NULL,
	
	Ma_DH VARCHAR(10) NOT NULL,
	Ma_KH VARCHAR(10) NOT NULL,
	Ma_TTKN INT NOT NULL DEFAULT 1,

	FOREIGN KEY (Ma_DH)
	REFERENCES DonHang(Ma_DH),

	FOREIGN KEY (Ma_KH)
	REFERENCES KhachHang(Ma_KH),

	FOREIGN KEY (Ma_TTKN)
	REFERENCES TinhTrangKN(Ma_TTKN),

)
-- xử lý khiếu nại 

GO 
CREATE TABLE XuLyKN 
(
	Ma_XLKN INT IDENTITY(1,1) NOT NULL,
	Ma_NV VARCHAR(10) NOT NULL,
	Ma_KN INT NOT NULL,

	NoiDung NTEXT NOT NULL,
	ThoiGian DATETIME NOT NULL,

	PRIMARY KEY (Ma_XLKN, Ma_NV, Ma_KN),
	FOREIGN KEY (Ma_NV)
	REFERENCES NhanVien(Ma_NV),

	FOREIGN KEY (Ma_KN)
	REFERENCES KhieuNai(Ma_KN)
)